import assert from 'node:assert/strict';
import {createHub} from '../src/hub/orchestrator.js';
import {createPipeline} from '../src/hub/pipeline.js';
import {createJobScope,StaleRunError} from '../src/lifecycle/jobs.js';
import {observePromptReceipt} from '../src/injection/receipt.js';
import {sceneDisplayState} from '../src/scene/display-state.js';
import {selectCapabilities} from '../src/shared/capabilities.js';
import {safeDetail} from '../src/debug/events.js';
import {createGenerationLifecycle} from '../src/lifecycle/generation.js';

let identity='chat:a';
const jobs=createJobScope(()=>identity);
const hub=createHub({jobs,getIdentity:()=>identity,StaleRunError});
let release,calls=0;
const held=new Promise(resolve=>{release=resolve;});
const task=run=>run.stage('decision',async()=>{calls++;await held;return {ok:true};},{module:'decision/request.js'});
const a=hub.run({key:'same',inputKey:'one'},task);
const b=hub.run({key:'same',inputKey:'one'},task);
assert.equal(a,b,'same owned run returns the same promise');
await Promise.resolve();release();await a;
assert.equal(calls,1);assert.equal(hub.snapshot().state.status,'prepared');
assert.ok(hub.snapshot().events.some(e=>e.code==='RUN_JOINED'));
let late;
const stale=hub.run({key:'stale'},run=>run.stage('retrieval',()=>new Promise(resolve=>{late=resolve;})));
await Promise.resolve();await Promise.resolve();identity='chat:b';late({});
assert.equal(await stale,null,'a result from a different chat cannot commit');
const timeout=hub.run({key:'timeout'},run=>run.stage('hung',()=>new Promise(()=>{}),{timeoutMs:15,module:'fixture'}));
await assert.rejects(timeout,error=>error.code==='WATCHDOG_TIMEOUT'&&error.stage==='hung');
assert.equal(hub.snapshot().state.status,'failed');
assert.ok(hub.snapshot().events.some(e=>e.code==='WATCHDOG_TIMEOUT'&&e.module==='fixture'));
let oldToken;
const obsoleteTimeout=hub.run({key:'obsolete'},run=>{oldToken=run;return run.stage('old',()=>new Promise(()=>{}),{timeoutMs:20});});
await Promise.resolve();await Promise.resolve();
identity='chat:current';hub.invalidate('chat_changed');
await hub.run({key:'current'},async()=>({ready:true}));
assert.equal(await obsoleteTimeout,null,'late watchdog expiry is cancellation after ownership changes');
assert.equal(oldToken.owns(),false);assert.equal(hub.snapshot().state.status,'prepared','late failure cannot replace the current status');
let prepared=0,unlock;
const prepareTask=()=>{prepared++;return new Promise(resolve=>{unlock=resolve;});};
const primary=hub.ensurePrepared({key:'cycle',trigger:'after_commands',request:{type:'normal'}},prepareTask);
const fallback=hub.ensurePrepared({key:'cycle',trigger:'interceptor'},prepareTask);
assert.equal(primary,fallback);let preparationReady=false;const awaited=hub.waitPrepared().then(()=>{preparationReady=true;});await Promise.resolve();assert.equal(preparationReady,false,'fallback waits for an unfinished primary before host assembly');unlock();await awaited;await primary;assert.equal(prepared,1);
hub.endCycle();await hub.ensurePrepared({key:'cycle',trigger:'after_commands'},()=>{prepared++;});assert.equal(prepared,2,'new generation is not deduplicated against a completed cycle');
await hub.ensurePrepared({key:'cycle',trigger:'after_commands'},()=>{prepared++;});assert.equal(prepared,3,'a fresh primary event always refreshes host registration even when input text is identical');
hub.commands.register('fixture.echo',value=>value);assert.equal(hub.commands.dispatch('fixture.echo',42),42);
hub.endCycle();
let completePrimary,completedFallback=false;
const ongoing=hub.ensurePrepared({key:'overlap',trigger:'after_commands',request:{type:'normal',inputKey:'input',sourceKey:'source',contextKey:'context'}},()=>new Promise(resolve=>{completePrimary=resolve;}));
await Promise.resolve();
const lifecycle=createGenerationLifecycle({hub,recentContext:()=>({contextKey:'context'}),currentInputKey:()=> 'input',sourceRevisionKey:()=> 'source',record:()=>({}),selectedWorld:()=>null});
const overlappingFallback=lifecycle.prepareFallback('normal').then(()=>{completedFallback=true;});
await Promise.resolve();assert.equal(completedFallback,false,'manifest fallback must await a primary still executing');
completePrimary();await ongoing;await overlappingFallback;assert.equal(completedFallback,true);
assert.throws(()=>hub.commands.register('fixture.echo',()=>{}),/중복/);
const order=[];
const pipeline=createPipeline({preparationCount:1,stages:[{stage:'context',module:'context',execute:(_run,frame)=>{order.push('context');frame.done=true;frame.result='paused';}},{stage:'decision',module:'decision',execute:()=>order.push('decision')}],onError:error=>{throw error;},finalize:()=>order.push('finalize')});
assert.equal(await hub.run({key:'early'},run=>pipeline(run)),'paused');assert.deepEqual(order,['context']);
const payload='A complete scene instruction.';
assert.equal(observePromptReceipt({messages:[{role:'system',content:payload}]},{payload}).scene,'confirmed');
assert.equal(observePromptReceipt({prompt:'other'},{payload}).scene,'unconfirmed');
assert.equal(observePromptReceipt({temperature:1},{payload}).scene,'unavailable');
assert.equal(observePromptReceipt({prompt:payload},{payload,dryRun:true}).observed,false);
for(let i=0;i<=4;i++)assert.equal(sceneDisplayState({level:i,phase:i>2?'active':'normal',route:i>2?'paused':'normal'}).stage,i);
assert.equal(sceneDisplayState({level:4,phase:'paused',route:'paused'}).stage,5);
assert.equal(sceneDisplayState({level:0,phase:'ended',route:'normal'}).stage,6);
assert.equal(sceneDisplayState({level:4,phase:'active',route:'paused',error:'failed'}).stage,null);
const data={value:1},service=Object.create(data);const selected=selectCapabilities(service,['value']);selected.value=2;assert.equal(data.value,2,'scoped writes reach the owning data object');
assert.deepEqual(safeDetail({secret:'abc',transcript:'private',payload:'private',payloadChars:4,inputKey:'id'}),{payloadChars:4,inputKey:'id'});
console.log('Hub runtime passed: deduplication, cancellation, watchdog, dual preparation, pipeline branching, command dispatch, prompt evidence, 0–6 display and capability ownership.');
