const fs=require('node:fs/promises'),path=require('node:path');
const {Worker}=require('node:worker_threads');
const {LIMITS,failure}=require('./limits.cjs');
const {read,location,atomic,safeDirectory,writer,safeFile}=require('./paths.cjs');
async function begin(root,{operationId,size,form}) {if(!Number.isSafeInteger(size)||size<1||size>LIMITS.documentBytes)throw failure('STORAGE_QUOTA','인물 JSON이 현재 등록 한도를 넘습니다.');const state=await require('./migration.cjs').progress(root);if(!['completed','cleaned','empty'].includes(state.status))throw failure('STORAGE_NOT_READY','자료 이사를 먼저 완료해 주세요.');if(state.status==='empty')await require('./transactions.cjs').writeDocument(root,'metadata:migration-v2',{schemaVersion:2,status:'completed',files:[],converted:[]});const file=location(root,'operations',operationId),prior=await read(file);if(prior){if(prior.kind!=='character_import'||prior.size!==size||JSON.stringify(prior.form)!==JSON.stringify(form))throw failure('STORAGE_CONFLICT','기존 업로드와 내용이 다릅니다.',409);return {operationId,status:prior.status};}await atomic(root,file,JSON.stringify({operationId,kind:'character_import',status:'preparing',size,form,createdAt:new Date().toISOString()}));return {operationId};}
async function part(root,{operationId,offset,data}) {const file=location(root,'operations',operationId),job=await read(file);if(job?.kind!=='character_import'||job.status!=='preparing')throw failure('STORAGE_INVALID_OPERATION','인물 파일 업로드를 확인하지 못했습니다.');if(typeof data!=='string'||data.length%4!==0||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(data))throw failure('STORAGE_CORRUPT','업로드 조각 형식이 올바르지 않습니다.');const bytes=Buffer.from(data,'base64');if(!bytes.length||bytes.length>LIMITS.partBytes||!Number.isSafeInteger(offset)||offset<0||offset+bytes.length>job.size)throw failure('STORAGE_QUOTA','업로드 조각 크기가 올바르지 않습니다.');return writer(root,async()=>{const upload=file+'.upload';let handle;try{await safeFile(root,upload);handle=await fs.open(upload,'r+');}catch(error){if(error.code!=='ENOENT')throw error;handle=await fs.open(upload,'wx',0o600);}try{const stat=await handle.stat();if(offset<stat.size){const prior=Buffer.alloc(bytes.length);await handle.read(prior,0,prior.length,offset);if(!prior.equals(bytes))throw failure('STORAGE_CONFLICT','재시도 파일 내용이 달라 저장하지 않았습니다.',409);return;}if(stat.size!==offset)throw failure('STORAGE_PART_MISSING','업로드 순서가 맞지 않습니다.');await handle.write(bytes,0,bytes.length,offset);await handle.sync();}finally{await handle.close();}});}
async function finish(root,{operationId},{signal}={}) {
 signal?.throwIfAborted();const file=location(root,'operations',operationId),job=await read(file);if(job?.kind!=='character_import')throw failure('STORAGE_INVALID_OPERATION','인물 파일을 확인하지 못했습니다.');if(job.status==='verified')return {outputs:job.outputs};if(job.status!=='preparing')throw failure('STORAGE_CANCELLED','취소된 인물 파일 확인입니다. 파일을 다시 선택해 주세요.');if((await fs.stat(file+'.upload')).size!==job.size)throw failure('STORAGE_PART_MISSING','파일 일부가 빠졌습니다.');
 return new Promise((resolve,reject)=>{const worker=new Worker(path.join(__dirname,'character-import-worker.mjs'),{workerData:{file:file+'.upload',root,form:job.form},resourceLimits:{maxOldGenerationSizeMb:768}});const abort=()=>{void worker.terminate();reject(failure('STORAGE_CANCELLED','인물 파일 확인을 취소했습니다.'));};signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(()=>{void worker.terminate();reject(failure('CHARACTER_IMPORT_TIMEOUT','인물 파일 확인 시간이 초과됐습니다. 기존 자료는 그대로 있어요.'));},180000);let settled=false;
 worker.once('message',async result=>{settled=true;clearTimeout(timer);try{signal?.throwIfAborted();if(!result.ok)throw failure(result.code,result.error);await atomic(root,file,JSON.stringify({...job,status:'verified',outputs:result.outputs}));await fs.unlink(file+'.upload');resolve({outputs:result.outputs});}catch(error){reject(error);}});worker.once('error',error=>{settled=true;clearTimeout(timer);reject(failure('CHARACTER_IMPORT_FAILED','인물 파일을 확인하지 못했습니다. 기존 자료는 그대로 있어요.'));});worker.once('exit',code=>{signal?.removeEventListener('abort',abort);if(!settled){clearTimeout(timer);reject(failure('CHARACTER_IMPORT_FAILED','인물 파일 확인이 중단됐습니다.'));}});
 });
}
module.exports={begin,part,finish};
