import { createJobScope, createWriteQueue } from "../lifecycle/jobs.js";
import { normalizeCharacterStore } from "../character/store.js";

export function createRuntimeState(stateChatKey) {
    return {
        worldInfoModule: null,
        lorebookRevisions: new Map(),
        jobs: createJobScope(() => stateChatKey()),
        queueWrite: createWriteQueue(),
        messageSnapshots: new Map(),
        chatRecords: new Map(),
        storageVersion: 0,
        hydrateSequence: 0,
        settings: undefined,
        dialog: undefined,
        judgeInFlight: false,
        judgeCompletionPromise: Promise.resolve(),
        resolveJudgeCompletion: null,
        macroAvailable: false,
        activeMacroPayload: '',
        activeWorldMacroPayload: '',
        activeInjectionPayload: '',
        activityToasts: new Map(),
        stateDbPromise: null,
        pendingGenerationType: '',
        generationMode: 'rp',
        debugInjectionArmed: false,
        activeGenerationCycle: { mode: 'rp', inputKey: '', startedAt: '' },
        chatReadyKey: null,
        diagnosticEvents: [],
        handledOocMarkers: [],
        serverStoreAvailable: false,
        serverKeyStatus: '확인 전',
        backupList: [],
        reasonerProfiles: [],
        reasonerProfileError: '',
        connectionRequestService: null,
        reasonerJobs: new Map(),
        reasonerGeneration: 0,
        pendingProfileStateCollection: Promise.resolve(),
        pendingProfileStateRequests: new Map(),
        profileStateSequence: 0,
        characterStore: normalizeCharacterStore(null),
        characterEditorKind: '',
        characterEditorId: '',
        characterAnalysisSelection: { kind: '', id: '' },
        privateOwnerPrompt: '',
        stateHistoryCache: new Map(),
    };
}
